name: Run AWS Login with keys

# Trigger - 4
'on':
  - push

permissions:
  id-token: write
  contents: read

jobs:
  AWS-login-and-test:
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        # Checks-out the repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      - name: Configure AWS Credentials using Access Key and Secret Key
        uses: aws-actions/configure-aws-credentials@v4.1.0
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: List S3 Buckets
        run: aws s3 ls

 
      # - name: '"Configure AWS Credentials" Action for GitHub Actions on runner'
      #   uses: aws-actions/configure-aws-credentials@v4.1.0
      #   with:
      #     aws-region: us-west-2
      #     role-to-assume: arn:aws:iam::438465144115:role/GitHubActions_PowerUser
      #     audience: sts.amazonaws.com
      #     retry-max-attempts: 3

         
